// Generated by build_hey.py from JaceThings/SF-Hello (Apple's SF Hello
// strokes). "hey" = h + e from hello-sv, the u bowl of hello-ro, the j
// descender of hello-sv, joined end to start. Units: SF Hello space,
// y up, baseline 0. One flat array per stroke: x0 y0 then c1 c2 p per segment.
#pragma once

namespace hey {

inline constexpr float kMinX = -109.061F;
inline constexpr float kMaxX = 1670.976F;
inline constexpr float kMinY = -314.521F;
inline constexpr float kMaxY = 737.156F;
inline constexpr float kStrokeWidth = 60.0F;

inline constexpr float kStroke0[] = {
    -109.061F, 95.926F,
    1.954F, 157.640F, 103.114F, 236.997F, 217.881F, 372.076F,
    296.000F, 464.285F, 338.000F, 569.573F, 340.000F, 642.194F,
    341.000F, 696.192F, 314.670F, 737.156F, 266.000F, 737.156F,
    212.000F, 737.156F, 178.000F, 696.192F, 157.000F, 602.161F,
    134.000F, 498.820F, 117.000F, 380.240F, 74.000F, 0.000F,
};

inline constexpr float kStroke1[] = {
    78.215F, 37.161F,
    100.229F, 230.683F, 184.000F, 372.000F, 291.000F, 372.000F,
    355.000F, 372.000F, 395.675F, 321.000F, 384.125F, 248.000F,
    377.624F, 205.000F, 370.087F, 161.000F, 361.306F, 110.000F,
    351.071F, 46.000F, 380.325F, -4.000F, 468.962F, -4.000F,
    598.225F, -4.000F, 739.244F, 67.834F, 811.412F, 179.094F,
    836.000F, 217.000F, 846.000F, 251.000F, 847.000F, 284.000F,
    848.000F, 344.000F, 814.000F, 389.000F, 754.000F, 389.000F,
    678.000F, 389.000F, 620.000F, 303.000F, 620.000F, 193.000F,
    620.000F, 75.000F, 684.000F, -8.000F, 810.774F, -8.000F,
    965.050F, -8.000F, 1092.714F, 115.238F, 1125.080F, 289.430F,
    1130.607F, 319.174F, 1138.416F, 350.598F, 1142.000F, 381.000F,
};

inline constexpr float kStroke2[] = {
    1142.000F, 381.000F,
    1124.721F, 307.940F, 1113.139F, 248.722F, 1106.985F, 204.722F,
    1101.873F, 172.722F, 1098.671F, 150.722F, 1097.424F, 123.722F,
    1095.772F, 52.721F, 1135.599F, 1.722F, 1212.605F, 1.722F,
    1324.605F, 1.722F, 1380.256F, 101.376F, 1413.998F, 264.813F,
    1422.068F, 303.902F, 1430.862F, 341.206F, 1437.976F, 380.479F,
};

inline constexpr float kStroke3[] = {
    1437.976F, 380.479F,
    1419.310F, 222.146F, 1400.643F, 63.813F, 1381.976F, -94.521F,
    1363.460F, -251.579F, 1316.976F, -314.521F, 1246.976F, -314.521F,
    1199.976F, -314.521F, 1165.976F, -284.591F, 1165.976F, -236.521F,
    1165.976F, -172.293F, 1214.717F, -126.184F, 1326.976F, -91.521F,
    1531.726F, -28.299F, 1617.938F, 44.204F, 1670.976F, 181.479F,
};

struct Stroke {
    const float *data;
    int count;  // floats
};

inline constexpr Stroke kStrokes[] = {
    {kStroke0, static_cast<int>(sizeof(kStroke0) / sizeof(float))},
    {kStroke1, static_cast<int>(sizeof(kStroke1) / sizeof(float))},
    {kStroke2, static_cast<int>(sizeof(kStroke2) / sizeof(float))},
    {kStroke3, static_cast<int>(sizeof(kStroke3) / sizeof(float))},
};

}  // namespace hey
